/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.Controller_Main;
/**
 *
 * @author JorgeIgnacio
 */
public class GUI_Car extends javax.swing.JPanel {

    Controller_Main controller_Main;//Reference
    /**
     * Creates new form GUI_Car
     */
    public GUI_Car() {
        initComponents();
        addControllerButtons(controller_Main);
    }
    
    public void addControllerButtons(Controller_Main controller_Main) {
        
        this.controller_Main = controller_Main;
        
        this.jB_Consult.addActionListener(controller_Main);
        this.jB_Add.addActionListener(controller_Main);
        this.jB_Modify.addActionListener(controller_Main);
        this.jB_Delete.addActionListener(controller_Main);
                
    }
    
    /*
    
    */
    public String[] get_jT_CarInformation() {
        
        String vector[] = new String[4];
        
        vector[0] = this.jT_RegistryNumber.getText();
        vector[1] = this.jT_OwnerName.getText();
        vector[2] = this.jT_Id_Owner.getText();
        vector[3] = this.jT_Id_Car.getText();
               
        return vector;
                
    }//End get_jT_CarInformation
    
    /*
    
    */
    public void set_jT_CarInformation(String vector[]) {
        
        this.jT_RegistryNumber.setText(vector[0]);
        this.jT_OwnerName.setText(vector[1]);
        this.jT_Id_Owner.setText(vector[2]);
        this.jT_Id_Car.setText(vector[3]);
                
    }//End set_jT_CarInformation
    
    /*
    
    */
    public String get_jT_RegistryNumber() {
        return this.jT_RegistryNumber.getText();
    }//End get_jT_RegistryNumber
    
    /*
    
    */
    public void clean_jT() {
        
        this.jT_RegistryNumber.setText("");
        this.jT_OwnerName.setText("");
        this.jT_Id_Owner.setText("");
        this.jT_Id_Car.setText("");
        
    }//End clean_jT
    
    public void addRegisterNumber(String registerNumber) {
        
        this.jT_RegistryNumber.setText(registerNumber);
        
    }
    
    public void initialState() {
        
        this.jB_Consult.setEnabled(false);
        this.jB_Modify.setEnabled(false);
        this.jB_Delete.setEnabled(false);
        
    }
    
    public void afterAdd() {
        
        this.jB_Consult.setEnabled(true);
        
    }//End afterAdd
    
    public void afterConsult() {
        
        this.jB_Consult.setEnabled(false);
        this.jB_Add.setEnabled(false);
        this.jB_Modify.setEnabled(true);
        this.jB_Delete.setEnabled(true);
        this.jT_RegistryNumber.setEnabled(false);
        
    }//End after odify
    
    public void afterModify_or_Delete() {
        
        this.jB_Consult.setEnabled(true);
        this.jB_Add.setEnabled(true);
        this.jB_Modify.setEnabled(false);
        this.jB_Delete.setEnabled(false);
        this.jT_RegistryNumber.setEnabled(true);
                
    }//End after odify  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_RegistryNumber = new javax.swing.JLabel();
        jT_RegistryNumber = new javax.swing.JTextField();
        jL_OwnerName = new javax.swing.JLabel();
        jT_OwnerName = new javax.swing.JTextField();
        jL_Owner = new javax.swing.JLabel();
        jT_Id_Owner = new javax.swing.JTextField();
        jL_idCar = new javax.swing.JLabel();
        jT_Id_Car = new javax.swing.JTextField();
        jB_Consult = new javax.swing.JButton();
        jB_Add = new javax.swing.JButton();
        jB_Modify = new javax.swing.JButton();
        jB_Delete = new javax.swing.JButton();

        jL_RegistryNumber.setText("REGISTRY NUMBER");

        jT_RegistryNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_RegistryNumberKeyPressed(evt);
            }
        });

        jL_OwnerName.setText("OWNER NAME");

        jL_Owner.setText("ID-OWNER");

        jL_idCar.setText("ID-CAR");

        jB_Consult.setText("CONSULT");

        jB_Add.setText("ADD");

        jB_Modify.setText("MODIFY");

        jB_Delete.setText("DELETE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jL_OwnerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_RegistryNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jT_RegistryNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_Id_Owner)
                                    .addComponent(jT_OwnerName)
                                    .addComponent(jT_Id_Car)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Consult, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_Modify)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_Delete)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jL_idCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jL_Owner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                        .addGap(6, 6, 6)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_RegistryNumber)
                    .addComponent(jT_RegistryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_OwnerName)
                    .addComponent(jT_OwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Owner)
                    .addComponent(jT_Id_Owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Id_Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_idCar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Delete)
                    .addComponent(jB_Consult)
                    .addComponent(jB_Add)
                    .addComponent(jB_Modify))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jT_RegistryNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_RegistryNumberKeyPressed
        
        if(evt.getKeyCode() == 10) {
            
            controller_Main.getMethodConsult();
            
        }
        
    }//GEN-LAST:event_jT_RegistryNumberKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Add;
    private javax.swing.JButton jB_Consult;
    private javax.swing.JButton jB_Delete;
    private javax.swing.JButton jB_Modify;
    private javax.swing.JLabel jL_Owner;
    private javax.swing.JLabel jL_OwnerName;
    private javax.swing.JLabel jL_RegistryNumber;
    private javax.swing.JLabel jL_idCar;
    private javax.swing.JTextField jT_Id_Car;
    private javax.swing.JTextField jT_Id_Owner;
    private javax.swing.JTextField jT_OwnerName;
    private javax.swing.JTextField jT_RegistryNumber;
    // End of variables declaration//GEN-END:variables
}
